//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISCAE.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Annonce
    {
        public int AnnonceId { get; set; }
        public string Titre { get; set; }
        public string Contenu { get; set; }
        public System.DateTime DateAjout { get; set; }
        public int AdministrateurId { get; set; }
    
        public virtual Administrateur Administrateur { get; set; }
    }
}
