//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISCAE.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentOfficiel
    {
        public int DocumentOfficielId { get; set; }
        public string Titre { get; set; }
        public string Emplacement { get; set; }
        public string Type { get; set; }
        public System.DateTime DateAjoutOfficiel { get; set; }
        public int ProfesseurId { get; set; }
        public int ModuleId { get; set; }
    
        public virtual Module Module { get; set; }
        public virtual Professeur Professeur { get; set; }
    }
}
