//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISCAE.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IscaeEntities : DbContext
    {
        public IscaeEntities()
            : base("name=IscaeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administrateur> Administrateurs { get; set; }
        public virtual DbSet<Annonce> Annonces { get; set; }
        public virtual DbSet<DocumentNonOfficiel> DocumentNonOfficiels { get; set; }
        public virtual DbSet<DocumentOfficiel> DocumentOfficiels { get; set; }
        public virtual DbSet<Etudiant> Etudiants { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<Module> Modules { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<ProfesseurModule> ProfesseurModules { get; set; }
        public virtual DbSet<Professeur> Professeurs { get; set; }
        public virtual DbSet<ProfesseurSpecialite> ProfesseurSpecialites { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<Recovery> Recoveries { get; set; }
        public virtual DbSet<Repons> Reponses { get; set; }
        public virtual DbSet<Resultat> Resultats { get; set; }
        public virtual DbSet<SpecialiteModule> SpecialiteModules { get; set; }
        public virtual DbSet<Specialite> Specialites { get; set; }
    }
}
