//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISCAE.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Question()
        {
            this.Reponses = new HashSet<Repons>();
        }
    
        public int QuestionId { get; set; }
        public string Contenu { get; set; }
        public string Titre { get; set; }
        public System.DateTime DateQuestion { get; set; }
        public string Attachment { get; set; }
        public int EtudiantId { get; set; }
    
        public virtual Etudiant Etudiant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Repons> Reponses { get; set; }
    }
}
