//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISCAE.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recovery
    {
        public int RecoveryId { get; set; }
        public string Matricule { get; set; }
        public string Email { get; set; }
        public string Code { get; set; }
    }
}
